### ISSUE TITLE
DEMO: Complete the implementation

### ISSUE THREAD

**Issue by gjwgit** [shashank-gv/hugging#11]

**Comment by shashank-gv** [comment]
Have included a basic demo command for now. 
`ml demo hugging (sentiment | summarize)` This will just provide the output on a sample input text. Will make this more verbose when trying to implement the visualisation with SHAP

**Comment by gjwgit** [comment]
You can model the demo command on the other mlhub packages, like kmeans. It should be a formatted interaction that explains the concepts and demonstrates the capability of the package, not just an interactive version of the commands.

**Comment by gjwgit** [comment]
As well as individual command demos without a command specified give a demo of all commands:

```bash
ml demo hugging
```
