### ISSUE TITLE
DEMO: A useful visualisation

### ISSUE THREAD

**Issue by gjwgit** [shashank-gv/hugging#12]
As you suggest, this could be a useful visualisation to include in the demo if there is some way to do so, or something similar.

https://shap.readthedocs.io/en/latest/example_notebooks/text_examples/summarization/Abstractive%20Summarization%20Explanation%20Demo.html

**Comment by shashank-gv** [comment]
I was playing around with the SHAP and from what I can see the output for the visualisations is an HTML object. I can't think of any way to render this directly from cli. One of the ways I was thinking of showing this was creating a jupyter notebook which renders the plots and can also contain supporting text (almost like a demo). I am not sure if this is the best way to go about it though (perhaps a blog post style notebook linked from the package catalogue? Or in the readme?)

**Comment by gjwgit** [comment]
The demo command could generate a rendering of the HTML to display as an image, if desired. Other mlhub packages display images as part of the demo and other commands (like in kmeans).

**Comment by gjwgit** [comment]
The plots shown in SHAP doco for the contribution mabe by words/phrases to the sentiment could be an optional output, and included in the demo.
