### ISSUE TITLE
SUMMARIZE: Make t5 as default and option for BERT in

### ISSUE THREAD

**Issue by shashank-gv** [shashank-gv/hugging#17]

**Comment by shashank-gv** [comment]
`ml summarize hugging https://www.abc.net.au/news/2022-09-22/nasa-releases-clearest-view-of-neptunes-rings-in-decades/101466864 --model BERT` will use BERT and the command defaults to using t5-small if no model is provided. Could expand this to include more models if needed (t5-large for example).

**Comment by gjwgit** [comment]
Yes, it would be good to include t5-large as another option. And others as available.
