### ISSUE TITLE
SUMMARIZE: Command line options need to give errors

### ISSUE THREAD

**Issue by gjwgit** [shashank-gv/hugging#19]
I haven't looked to see what is going on here but this should give an error if the option is not used. The following uses t5-small. I didn't  expect `--m` should work, but it does not complain.

```bash
ml summarize hugging --m=bert https://www.abc.net.au/news/2022-08-16/morrison-secret-ministerial-appointments-legal-or-not-icac/101318718
```

Noting that the following works just fine and uses bert:

```bash
ml summarize hugging --mo=bert https://www.abc.net.au/news/2022-08-16/morrison-secret-ministerial-appointments-legal-or-not-icac/101318718
```

**Comment by shashank-gv** [comment]
Should give you an error for unsuppported/invalid models
