### ISSUE TITLE
SUMMARIZE: Have summarise as a synonym for summarize

### ISSUE THREAD

**Issue by gjwgit** [shashank-gv/hugging#20]
How would we go about having the following two do the same thing:

```bash
ml summarise hugging news.txt
```

and

```bash
ml summarize hugging news.txt
```

**Comment by shashank-gv** [comment]
Added summarise as another command and simply called `summarize.main()` in `summarise.py`

**Comment by gjwgit** [comment]
Perhaps don't need to list summarise in the mlhub.yaml list of commands - is there any downside not listing it?

**Comment by shashank-gv** [comment]
Yep, summarise isn't required. I thought mlhub required it under commands to run the python file but that is not the case. Have removed it now.
