### ISSUE TITLE
SENTIMENT: Handle different text pathways

### ISSUE THREAD

**Issue by gjwgit** [shashank-gv/hugging#24]
All of the following should be supported:

- [x] `ml sentiment hugging The best is yet to come` This returns the sentiment of the text on the command line.
- [x] `ml sentiment hugging news.txt` This reads the text for the file if it exists
- [x] `cat news.txt | ml sentiment hugging` This reads the text input from STDIN
- [x] `ml sentiment hugging` This will prompt user for input text

See the [aztext](https://github.com/gjwgit/aztext) package for some example code.

For the name file version, check if there is a single argument, and if so, does the named file exist, and if not, does it look like a filename, and if so generate a file not found error, but if it doesn't look like a file name generate the sentiment of the word.

**Comment by shashank-gv** [comment]
`sentiment` should be able to handle these pathways now
