### ISSUE TITLE
SUMMARIZE: accept a URL

### ISSUE THREAD

**Issue by gjwgit** [shashank-gv/hugging#5]
This would be a useful feature:

```
ml summarize hugging https://www.abc.net.au/news/2022-08-16/morrison-secret-ministerial-appointments-legal-or-not-icac/101318718
```

Could be difficult to get just the text though.

Worth a try?

**Comment by shashank-gv** [comment]
I have updated the code to now accept urls as input. There is a slight bug (which I found a hacky way around). Will elaborate on this in Teams.
So this command `ml summarize hugging https://www.abc.net.au/news/2022-08-16/morrison-secret-ministerial-appointments-legal-or-not-icac/101318718` should work

**Comment by gjwgit** [comment]
Tested - working great. Thanks.
