### ISSUE TITLE
SENTIMENT: Use __main__ in the code

### ISSUE THREAD

**Issue by gjwgit** [shashank-gv/hugging#7]
It's good practise to use something like the following for code that is meant to be run as a standalone command (as well, perhaps, as a library file). 

```
if __name__ == "__main__":
    cli(prog_name="sentiment")
```

**Comment by shashank-gv** [comment]
Have included `__name__ == "__main__"` in the code for summarize.py and sentiment.py but I'm not sure if this is how you wanted it. Did you want it more modular with main containing just a single function?

**Comment by gjwgit** [comment]
Often the body for the command line interface might be in a function (e.g., cli()) and then the __main__ part is like:

if __name__ == "__main__":
    cli(prog_name="sentiment")

The kmeans package does it this way. It is a little cleaner and if I want to swap in a different main function it is a lot easier.
