### ISSUE TITLE
SENTIMENT: Do a lint check on the code

### ISSUE THREAD

**Issue by gjwgit** [shashank-gv/hugging#8]
I am seeing the following lint/format problems in the code:

![image](https://user-images.githubusercontent.com/1681429/186986666-46eca324-9db1-4194-a8f6-5c579a9d8da2.png)

From `$ flake8 sentiment.py`

- [ ] sentiment.py:13:1: E302 expected 2 blank lines, found 1
- [ ] sentiment.py:18:25: E231 missing whitespace after ','
- [ ] sentiment.py:21:1: E305 expected 2 blank lines after class or function definition, found 1
- [ ] sentiment.py:21:45: E251 unexpected spaces around keyword / parameter equals
- [ ] sentiment.py:21:80: E501 line too long (116 > 79 characters)
- [ ] sentiment.py:29:1: E722 do not use bare 'except'
- [ ] sentiment.py:33:80: E501 line too long (105 > 79 characters)
- [ ] sentiment.py:35:30: W292 no newline at end of file`

**Comment by shashank-gv** [comment]
Should be fixed now
